In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pprint as pp
# import IPython
# from IPython.display import display, HTML
# from IPython.core.interactiveshell import InteractiveShell

# InteractiveShell.ast_node_interactivity = "all"
# CSS = """
# .output {
#     flex-direction: row;
# }
# """
# HTML('<style>{}</style>'.format(CSS))

---

## Cleaning/Mapping for tidy data.

Contained is primary dataset (`../0826export.csv`) which we will prepare for analysis. To help with this task we also have have another data set(`../store_master.xlsx`) which we will merge, map onto, and otherwise tidy up our primary dataset with.

In [52]:
df1 = pd.read_csv('./data/0826export.csv')
# df1.columns = df1.columns.str.lower()

df2 = pd.read_excel('./documentation/store_master.xlsx')
# df2.columns = df2.columns.str.lower()

In [6]:
# column creation and mapping
#############################
# store class column
df2_store_dict = dict(zip(df2['store'], df2['class']))
df1['class'] = df1['store'].map(df2_store_dict)

# store city column 
df2_city_dict = dict(zip(df2['store'], df2['store_city']))
df1['city'] = df1['store'].map(df2_city_dict)

# store state column
df2_state_dict = dict(zip(df2['store'], df2['store_state']))
df1['state'] = df1['store'].map(df2_state_dict)

# store close date
df2_closed_dict = dict(zip(df2['store'], df2['close_date']))
df1['close_date'] = df1['store'].map(df2_closed_dict)

df2_ft_dict = dict(zip(df2['store'], df2['gross_feet']))
df1['gross_feet'] = df1['store'].map(df2_ft_dict)

In [27]:
# df1.dtypes.value_counts()
# df1.select_dtypes('O')
# df1.select_dtypes('int64')['fiscal_week']
# df1.select_dtypes('float64').columns
df1.iloc[:,:]

,div,store,week_end_date,fiscal_year,fiscal_week,fiscal_month,sales_amt_ty,sales_amt_ly,comp_pct,fiscal_year_ly,...,pt_tenure_days,avg_pt_tenure_days,num_of_emps,tot_tenure_days,tot_avg_tenure_days,class,city,state,close_date,gross_feet
0,7,1504,06-FEB-16,2017,1,1,22003.18,21266.87,0.034622,2016,...,47,47.0,4,1267,317,Mall,LAS VEGAS,NV,NaN,1849
1,7,1504,13-FEB-16,2017,2,1,17499.35,23490.64,-0.255050,2016,...,54,54.0,4,1295,324,Mall,LAS VEGAS,NV,NaN,1849
2,7,1504,20-FEB-16,2017,3,1,15004.60,22318.80,-0.327715,2016,...,61,61.0,4,1323,331,Mall,LAS VEGAS,NV,NaN,1849
3,7,1504,27-FEB-16,2017,4,1,12770.09,17296.40,-0.261691,2016,...,68,68.0,4,1351,338,Mall,LAS VEGAS,NV,NaN,1849
4,7,1504,05-MAR-16,2017,5,2,19920.51,24553.82,-0.188700,2016,...,75,75.0,4,1379,345,Mall,LAS VEGAS,NV,NaN,1849
5,7,1504,12-MAR-16,2017,6,2,16906.51,19484.63,-0.132316,2016,...,82,82.0,4,1407,352,Mall,LAS VEGAS,NV,NaN,1849
6,7,1504,19-MAR-16,2017,7,2,18074.96,11267.89,0.604112,2016,...,89,89.0,4,1435,359,Mall,LAS VEGAS,NV,NaN,1849
7,7,1504,26-MAR-16,2017,8,2,15263.72,28198.95,-0.458713,2016,...,96,96.0,4,1463,366,Mall,LAS VEGAS,NV,NaN,1849
8,7,1504,02-APR-16,2017,9,3,19582.20,16395.94,0.194332,2016,...,106,53.0,5,1494,299,Mall,LAS VEGAS,NV,NaN,1849
9,7,1504,09-APR-16,2017,10,3,20684.58,20056.50,0.031316,2016,...,120,60.0,5,1529,306,Mall,LAS VEGAS,NV,NaN,1849
10,7,1504,16-APR-16,2017,11,3,15122.71,11841.61,0.277082,2016,...,134,67.0,5,1564,313,Mall,LAS VEGAS,NV,NaN,1849
11,7,1504,23-APR-16,2017,12,3,19203.37,12633.88,0.519990,2016,...,148,74.0,5,1599,320,Mall,LAS VEGAS,NV,NaN,1849
12,7,1504,30-APR-16,2017,13,3,20899.00,17580.11,0.188787,2016,...,162,81.0,5,1634,327,Mall,LAS VEGAS,NV,NaN,1849
13,7,1504,07-MAY-16,2017,14,4,26574.28,19787.29,0.342997,2016,...,176,88.0,5,1669,334,Mall,LAS VEGAS,NV,NaN,1849
14,7,1504,14-MAY-16,2017,15,4,12520.88,18931.04,-0.338606,2016,...,190,95.0,5,1704,341,Mall,LAS VEGAS,NV,NaN,1849
15,7,1504,21-MAY-16,2017,16,4,16006.67,16870.56,-0.051207,2016,...,158,79.0,6,1745,291,Mall,LAS VEGAS,NV,NaN,1849
16,7,1504,28-MAY-16,2017,17,4,17246.05,14707.89,0.172571,2016,...,172,86.0,6,1787,298,Mall,LAS VEGAS,NV,NaN,1849
17,7,1504,04-JUN-16,2017,18,5,17261.42,16736.94,0.031337,2016,...,186,93.0,6,1829,305,Mall,LAS VEGAS,NV,NaN,1849
18,7,1504,11-JUN-16,2017,19,5,19706.61,17835.65,0.104900,2016,...,200,100.0,6,1871,312,Mall,LAS VEGAS,NV,NaN,1849
19,7,1504,18-JUN-16,2017,20,5,17608.54,17095.97,0.029982,2016,...,214,107.0,6,1913,319,Mall,LAS VEGAS,NV,NaN,1849
20,7,1504,25-JUN-16,2017,21,5,12599.97,12896.89,-0.023023,2016,...,228,114.0,6,1955,326,Mall,LAS VEGAS,NV,NaN,1849
21,7,1504,02-JUL-16,2017,22,6,15144.95,12942.91,0.170135,2016,...,242,121.0,6,1997,333,Mall,LAS VEGAS,NV,NaN,1849
22,7,1504,09-JUL-16,2017,23,6,11133.11,10849.13,0.026175,2016,...,256,128.0,6,2039,340,Mall,LAS VEGAS,NV,NaN,1849
23,7,1504,16-JUL-16,2017,24,6,12567.96,13368.98,-0.059916,2016,...,270,135.0,6,2081,347,Mall,LAS VEGAS,NV,NaN,1849
24,7,1504,23-JUL-16,2017,25,6,14977.31,19194.23,-0.219697,2016,...,284,142.0,6,2123,354,Mall,LAS VEGAS,NV,NaN,1849
25,7,1504,30-JUL-16,2017,26,6,14795.54,17764.97,-0.167151,2016,...,298,149.0,6,2165,361,Mall,LAS VEGAS,NV,NaN,1849
26,7,1504,06-AUG-16,2017,27,7,13948.54,16082.99,-0.132715,2016,...,312,156.0,6,2207,368,Mall,LAS VEGAS,NV,NaN,1849
27,7,1504,13-AUG-16,2017,28,7,13736.29,13946.15,-0.015048,2016,...,326,163.0,6,2249,375,Mall,LAS VEGAS,NV,NaN,1849
28,7,1504,20-AUG-16,2017,29,7,15892.23,15442.58,0.029118,2016,...,340,170.0,6,2291,382,Mall,LAS VEGAS,NV,NaN,1849
29,7,1504,27-AUG-16,2017,30,7,14913.68,13208.36,0.129109,2016,...,354,177.0,6,2333,389,Mall,LAS VEGAS,NV,NaN,1849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27163,7,2089,05-JAN-19,2019,48,12,26980.06,16882.56,0.598102,2018,...,708,236.0,6,1824,304,Outlet,CHANDLER,AZ,NaN,2714
27164,7,2089,12-JAN-19,2019,49,12,13369.45,14039.26,-0.047710,2018,...,729,243.0,6,1866,311,Outlet,CHANDLER,AZ,NaN,2714
27165,7,2089,19-JAN-19,2019,50,12,14302.18,15721.43,-0.090275,2018,...,750,250.0,6,1908,318,Outlet,CHANDLER,AZ,NaN,2714
27166,7,2089,26-JAN-19,2019,51,12,14427.25,11516.19,0.252780,2018,...,771,257.0,6,1950,325,Outlet,CHANDLER,AZ,NaN,2714
27167,7,2089,02-FEB-19,2019,52,12,16337.85,16255.01,0.005096,2018,...,792,264.0,6,1992,332,Outlet,CHANDLER,AZ,NaN,2714
27168,7,2089,09-FEB-19,2020,1,1,16753.80,14299.09,0.171669,2019,...,813,271.0,6,2034,339,Outlet,CHANDLER,AZ,NaN,2714
27169,7,2089,16-FEB-19,2020,2,1,16786.35,18283.81,-0.081901,2019,...,838,209.5,7,2080,297,Outlet,CHANDLER,AZ,NaN,2714
27170,7,2089,23-FEB-19,2020,3,1,18076.80,20614.63,-0.123108,2019,...,866,216.5,6,1622,270,Outlet,CHANDLER,AZ,NaN,2714
27171,7,2089,02-MAR-19,2020,4,1,17354.12,16633.07,0.043350,2019,...,894,223.5,6,1664,277,Outlet,CHANDLER,AZ,NaN,2714
27172,7,2089,09-MAR-19,2020,5,2,16071.44,16971.86,-0.053054,2019,...,922,230.5,6,1706,284,Outlet,CHANDLER,AZ,NaN,2714
27173,7,2089,16-MAR-19,2020,6,2,23845.72,23949.91,-0.004350,2019,...,950,237.5,6,1748,291,Outlet,CHANDLER,AZ,NaN,2714
27174,7,2089,23-MAR-19,2020,7,2,19552.47,22158.03,-0.117590,2019,...,978,244.5,6,1790,298,Outlet,CHANDLER,AZ,NaN,2714
27175,7,2089,30-MAR-19,2020,8,2,15803.12,27636.36,-0.428177,2019,...,1006,251.5,6,1832,305,Outlet,CHANDLER,AZ,NaN,2714
27176,7,2089,06-APR-19,2020,9,3,16489.52,19929.90,-0.172624,2019,...,981,327.0,5,1821,364,Outlet,CHANDLER,AZ,NaN,2714
27177,7,2089,13-APR-19,2020,10,3,17962.28,25591.87,-0.298126,2019,...,1002,334.0,5,1856,371,Outlet,CHANDLER,AZ,NaN,2714
27178,7,2089,27-APR-19,2020,12,3,16147.80,15864.74,0.017842,2019,...,1044,348.0,5,1926,385,Outlet,CHANDLER,AZ,NaN,2714
27179,7,2089,04-MAY-19,2020,13,3,16338.13,19378.30,-0.156885,2019,...,1065,355.0,5,1961,392,Outlet,CHANDLER,AZ,NaN,2714
27180,7,2089,11-MAY-19,2020,14,4,16747.76,15407.02,0.087021,2019,...,1086,362.0,5,1996,399,Outlet,CHANDLER,AZ,NaN,2714
27181,7,2089,18-MAY-19,2020,15,4,13076.55,17427.95,-0.249679,2019,...,1107,369.0,5,2031,406,Outlet,CHANDLER,AZ,NaN,2714
27182,7,2089,25-MAY-19,2020,16,4,16512.15,20696.32,-0.202170,2019,...,1128,376.0,5,2066,413,Outlet,CHANDLER,AZ,NaN,2714
27183,7,2089,01-JUN-19,2020,17,4,17379.27,17276.98,0.005921,2019,...,1149,383.0,5,2101,420,Outlet,CHANDLER,AZ,NaN,2714
27184,7,2089,08-JUN-19,2020,18,5,13113.18,12833.34,0.021806,2019,...,1170,390.0,5,2136,427,Outlet,CHANDLER,AZ,NaN,2714
27185,7,2089,15-JUN-19,2020,19,5,11650.91,18349.61,-0.365060,2019,...,1191,397.0,5,2171,434,Outlet,CHANDLER,AZ,NaN,2714
27186,7,2089,22-JUN-19,2020,20,5,11129.46,13853.55,-0.196635,2019,...,1212,404.0,5,2206,441,Outlet,CHANDLER,AZ,NaN,2714
27187,7,2089,29-JUN-19,2020,21,5,8200.96,12881.71,-0.363364,2019,...,1233,411.0,5,2241,448,Outlet,CHANDLER,AZ,NaN,2714
27188,7,2089,06-JUL-19,2020,22,6,14397.25,15654.98,-0.080341,2019,...,1254,418.0,5,2276,455,Outlet,CHANDLER,AZ,NaN,2714
27189,7,2089,13-JUL-19,2020,23,6,11424.20,11137.42,0.025749,2019,...,1275,425.0,5,2311,462,Outlet,CHANDLER,AZ,NaN,2714
27190,7,2089,20-JUL-19,2020,24,6,10366.48,12987.83,-0.201831,2019,...,1296,432.0,6,2348,391,Outlet,CHANDLER,AZ,NaN,2714
27191,7,2089,27-JUL-19,2020,25,6,12977.11,15016.29,-0.135798,2019,...,1317,439.0,6,2390,398,Outlet,CHANDLER,AZ,NaN,2714
27192,7,2089,03-AUG-19,2020,26,6,11824.40,13970.76,-0.153632,2019,...,471,471.0,4,1565,391,Outlet,CHANDLER,AZ,NaN,2714

109

In [5]:
# df_closed
df_closed = df1[df1['close_date'].notnull()].drop('div', axis=1)
# df_closed = df_closed.groupby(['store','fiscal_year','fiscal_month'])['comp_pct']
# df_closed = df_closed.groupby('store')
# df_closed.head()
df_closed['week_end_date'] = df_closed['week_end_date'].apply(lambda x: pd.to_datetime(x))

---

## Selecing Column Variables for doing a correlation

In [274]:
# new = closed_stripped_df.groupby(['store','fiscal_year'])['comp_pct'].mean().unstack().reset_index()
# new = closed_stripped_df.groupby(['store','fiscal_year']).sum()
# new = df_closed[:, [1,3,8,15,16,17,18,19,20, 27,28,29,30,31,32,33,34,35,36,55,56,57,58,59,60,61,
#                    62,63,64,65,66,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,99,
#                   100,101,102,103,104,105,106,107,108]]

# df_closed

---

## Grouping TEST CELL BELOW

In [ ]:

####################################
####################################

# df_pivot = df1.pivot_table(values='comp_pct', index=['store'],columns='fiscal_year')#.nlargest(10, 'fiscal_year')
# df_pivot['comp_pct_sum'] = df_pivot[2017] + df_pivot[2018] + df_pivot[2019] + df_pivot[2020]
# df_pivot.nsmallest(10, 'comp_pct_sum')
    
    
####################################
####################################

# df1.groupby('store')['comp_pct'].sum().nsmallest(10)
# df1[['gross_feet', 'comp_pct']].groupby('comp_pct')['gross_feet'].value_counts(bins=20)#.plot(kind='scatter');
# df1[['gross_feet', 'comp_pct']].groupby('gross_feet').mean().hist(bins=40);

In [130]:
# grouped_class_comp_sum = df1.groupby(['class'])['comp_pct'].sum() # keep these
# grouped_class_comp_mean = df1.groupby(['class'])['comp_pct'].mean() # keep these

# grouped_store_comp_sum = df1.groupby(['store'])['comp_pct'].sum() # keep these
# grouped_store_comp_mean = df1.groupby(['store'])['comp_pct'].mean() # keep these

grouped_store = df_closed.groupby(['fiscal_year','store'])[['comp_pct', 
                                                            'strak_transaction_num', 
                                                            'tot_avg_tenure_days','city',
                                                            'state','gross_feet']].sum()
# grouped_city_comp_sum.nlargest(10)
# grouped_class_comp_sum.nlargest(10)

# grouped_store.index
grouped_store.xs((2017, 1643), axis=0)

comp_pct                    -8.341135
strak_transaction_num     3561.000000
tot_avg_tenure_days       4206.000000
gross_feet               43378.000000
Name: (2017, 1643), dtype: float64

In [2]:
# grouped_store_comp_mean.nsmallest(10)
# grouped_store_comp_sum.nsmallest(10)
# mc(pd.core.groupby.generic.DataFrameGroupBy)
# dir(grouped_store.index)

In [ ]:
grouped_store_pct_largest = df1.groupby(['store'])['comp_pct', 
                                          'accessory_units',
                                          'trans_cnt_sales',
                                          'trans_cnt_total',
                                          'accessory_units'].sum().nlargest(10, 'comp_pct')

grouped_store_pct_smallest = df1.groupby(['store'])['comp_pct', 
                                          'accessory_units',
                                          'trans_cnt_sales',
                                          'trans_cnt_total',
                                          'accessory_units'].sum().nsmallest(10, 'comp_pct')

In [ ]:
# grouped_store_pct_largest.corr()
# grouped_store_pct_smallest.corr()

In [ ]:
# grouped_store_pct_largest
# grouped_store_pct_smallest

In [401]:
grouped_store_pct_smallest = df1.groupby(['store'])['comp_pct', 
                                          'accessory_units',
                                          'trans_cnt_sales',
                                          'trans_cnt_total',
                                          'accessory_units'].sum()

grouped_store_pct_smallest.nsmallest(10, 'comp_pct')

,comp_pct,accessory_units,trans_cnt_sales,trans_cnt_total,accessory_units
store,,,,,
1643,-13.529220,6449,5682,6763,6449
1803,-12.364402,17716,10311,12015,17716
1817,-11.544135,29302,14335,16638,29302
1600,-10.686017,13721,12220,14429,13721
2067,-8.856854,29207,16848,18444,29207
1717,-7.597681,21186,12396,12850,21186
1504,-6.772227,27988,14272,15371,27988
1849,-6.053967,4412,3127,3912,4412
1672,-4.967440,14585,10132,12204,14585
1854,-4.891813,73684,39649,44854,73684

In [7]:
main_data = pd.read_csv('./data/0826export.csv')

main_data.rename(columns={'AVG_FOOTWEWAR_PRICE':'AVG_FOOTWEAR_PRICE'},inplace=True)

chosen_columns_df = pd.read_excel('./data/nss_dict_COLUMNS to use.xlsb.xlsx', sheet_name=1, index_col='DATA ORDER')

chosen_columns_df = chosen_columns_df.dropna().drop('COLUMNS TO KEEP', axis=1)

main_data = main_data[chosen_columns_df.COLUMN.to_list()]

42

In [8]:
main_data.to_csv('./data/0826export_column_filter_1.csv', index=False)

In [136]:
len(df1.columns)

42

In [ ]:
pd?.read_csv